### PR TITLE
fix `ListItem` definition

### LINKED ISSUE #401: Fix `ListItem` definition
When run in circuit context, the `Payload` argument for `ListItem` ends up containing the whole circuit type, leading to the recursive definition of input payload, which fails to typecheck.

We need to change the definition of `ListItem` so that stops being the case and circuit compiles fine.

### PR DESCRIPTION
**Pull request by TurtlePU**
Resolves #401

### CODE REVIEW

File: symbolic-base/src/ZkFold/Symbolic/Data/List.hs [hunk 1]
```diff
@@ -29,30 +29,22 @@ import           ZkFold.Symbolic.Data.Payloaded   (Payloaded (Payloaded))
...
-    Distributive (ListItem x) where
+instance (Representable l, Representable p) => Distributive (ListItem l p) where
   distribute = distributeRep
 
-instance
-  (Representable (Layout x), Representable (Payload x)) =>
-  Representable (ListItem x)
+instance (Representable l, Representable p) => Representable (ListItem l p)
 
 data List c x = List
```
Comment (echatav) [inline symbolic-base/src/ZkFold/Symbolic/Data/List.hs:44]: Is there any reason we need to parameterize `List` by its context `c` since it can be determined from `x` as `Context x` just as `Layout x` & `Payload x` are?

Comment (TurtlePU) [reply symbolic-base/src/ZkFold/Symbolic/Data/List.hs:44]: A good question, actually
I think we can, same in `Maybe`
We can create an issue abt this

Comment (TurtlePU) [reply symbolic-base/src/ZkFold/Symbolic/Data/List.hs:44]: #415

**Review by vlasin — APPROVED** [review]
